In [24]:
# Python program explaining
# eig() function
import numpy as np

In [25]:
from numpy import linalg as geek

In [26]:
# Creating an array using diag 
# function
a = np.diag((1, 2, 3))

In [27]:
print("Array is :",a)


Array is : [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [28]:
# calculating an eigen value
# using eig() function
c, d = geek.eig(a)

In [29]:
print("Eigen value is :",c)


Eigen value is : [1. 2. 3.]


In [30]:
print("Eigen value is :",d)


Eigen value is : [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
