In [1]:
import numpy as np

In [3]:
# Creating a rank 1 Array
arr = np.array([1, 2, 3])
print("Array with Rank 1: \n",arr)

Array with Rank 1: 
 [1 2 3]


In [4]:
# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)

Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]


In [5]:
# Creating an array from tuple
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)


Array created using passed tuple:
 [1 3 2]
